- name: Upload to S3 and Deploy to Lambda
        run: |
          aws s3 cp deployment.zip s3://nifty-quant-desk-logs-2026/deployment.zip
          aws lambda update-function-code \
            --function-name nifty_options_engine \
            --s3-bucket nifty-quant-desk-logs-2026 \
            --s3-key deployment.zip \
            --region ap-south-1